name: shoes_shopping_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  cupertino_icons:
  iconsax:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family: Futura
      fonts:
        - asset: assets/font/futura.ttf
    - family: Muli
      fonts:
        - asset: assets/font/muli/Muli.ttf
        - asset: assets/font/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/font/muli/Muli-Light.ttf
          weight: 300